// Car database. Specs are manufacturer/press figures for the listed generation.
// `body` drives silhouettes + recognition matching; `rarity` drives XP and card framing.

export const RARITY = {
  common: { label: 'Common', color: '#8fa3b0', xp: 10, weight: 1.0 },
  uncommon: { label: 'Uncommon', color: '#4ade80', xp: 25, weight: 0.55 },
  rare: { label: 'Rare', color: '#38bdf8', xp: 60, weight: 0.25 },
  epic: { label: 'Epic', color: '#c084fc', xp: 150, weight: 0.08 },
  legendary: { label: 'Legendary', color: '#fbbf24', xp: 400, weight: 0.02 },
};

export const BODIES = {
  sedan: 'Sedan',
  coupe: 'Coupe',
  convertible: 'Convertible',
  hatchback: 'Hatchback',
  wagon: 'Wagon',
  suv: 'SUV',
  pickup: 'Pickup',
  van: 'Van',
  minivan: 'Minivan',
};

export const CARS = [
  // ---------------------------------------------------------------- common
  {
    id: 'toyota-corolla', make: 'Toyota', model: 'Corolla', years: '2020–2025',
    body: 'sedan', country: 'Japan', rarity: 'common',
    engine: '2.0L naturally aspirated I4', power: 169, torque: 151,
    zeroToSixty: 8.2, topSpeed: 118, drivetrain: 'FWD', transmission: 'CVT',
    weight: 3150, mpg: 35, seats: 5,
    blurb: 'The best-selling nameplate in automotive history. If you scan exactly one car today, statistically this is it.',
  },
  {
    id: 'honda-civic', make: 'Honda', model: 'Civic', years: '2022–2025',
    body: 'sedan', country: 'Japan', rarity: 'common',
    engine: '2.0L naturally aspirated I4', power: 158, torque: 138,
    zeroToSixty: 8.2, topSpeed: 125, drivetrain: 'FWD', transmission: 'CVT',
    weight: 2900, mpg: 35, seats: 5,
    blurb: 'Eleventh-generation Civic. The default first car of an entire continent.',
  },
  {
    id: 'toyota-camry', make: 'Toyota', model: 'Camry', years: '2018–2024',
    body: 'sedan', country: 'Japan', rarity: 'common',
    engine: '2.5L naturally aspirated I4', power: 203, torque: 184,
    zeroToSixty: 7.6, topSpeed: 135, drivetrain: 'FWD', transmission: '8-speed automatic',
    weight: 3310, mpg: 32, seats: 5,
    blurb: 'Aggressively sensible. The XSE trim has a fake exhaust tip and everybody knows it.',
  },
  {
    id: 'honda-accord', make: 'Honda', model: 'Accord', years: '2018–2022',
    body: 'sedan', country: 'Japan', rarity: 'common',
    engine: '1.5L turbocharged I4', power: 192, torque: 192,
    zeroToSixty: 7.2, topSpeed: 130, drivetrain: 'FWD', transmission: 'CVT',
    weight: 3150, mpg: 33, seats: 5,
    blurb: 'A midsize sedan that handles better than it has any obligation to.',
  },
  {
    id: 'nissan-altima', make: 'Nissan', model: 'Altima', years: '2019–2025',
    body: 'sedan', country: 'Japan', rarity: 'common',
    engine: '2.5L naturally aspirated I4', power: 188, torque: 180,
    zeroToSixty: 7.6, topSpeed: 130, drivetrain: 'FWD', transmission: 'CVT',
    weight: 3210, mpg: 32, seats: 5,
    blurb: 'Ubiquitous rental-lot royalty.',
  },
  {
    id: 'hyundai-elantra', make: 'Hyundai', model: 'Elantra', years: '2021–2025',
    body: 'sedan', country: 'South Korea', rarity: 'common',
    engine: '2.0L naturally aspirated I4', power: 147, torque: 132,
    zeroToSixty: 8.8, topSpeed: 125, drivetrain: 'FWD', transmission: 'CVT',
    weight: 2900, mpg: 37, seats: 5,
    blurb: 'Origami bodywork on a commuter budget.',
  },
  {
    id: 'vw-jetta', make: 'Volkswagen', model: 'Jetta', years: '2019–2025',
    body: 'sedan', country: 'Germany', rarity: 'common',
    engine: '1.5L turbocharged I4', power: 158, torque: 184,
    zeroToSixty: 7.8, topSpeed: 126, drivetrain: 'FWD', transmission: '8-speed automatic',
    weight: 3000, mpg: 36, seats: 5,
    blurb: 'German-adjacent, built in Puebla, priced like a Corolla.',
  },
  {
    id: 'toyota-prius', make: 'Toyota', model: 'Prius', years: '2023–2025',
    body: 'hatchback', country: 'Japan', rarity: 'common',
    engine: '2.0L I4 hybrid', power: 194, torque: 139,
    zeroToSixty: 7.1, topSpeed: 112, drivetrain: 'FWD', transmission: 'eCVT',
    weight: 3200, mpg: 57, seats: 5,
    blurb: 'The fifth-gen Prius got genuinely attractive, which nobody was prepared for.',
  },
  {
    id: 'toyota-rav4', make: 'Toyota', model: 'RAV4', years: '2019–2025',
    body: 'suv', country: 'Japan', rarity: 'common',
    engine: '2.5L naturally aspirated I4', power: 203, torque: 184,
    zeroToSixty: 8.0, topSpeed: 116, drivetrain: 'AWD', transmission: '8-speed automatic',
    weight: 3490, mpg: 30, seats: 5,
    blurb: 'Outsells most countries’ entire domestic industries.',
  },
  {
    id: 'honda-crv', make: 'Honda', model: 'CR-V', years: '2023–2025',
    body: 'suv', country: 'Japan', rarity: 'common',
    engine: '1.5L turbocharged I4', power: 190, torque: 179,
    zeroToSixty: 7.9, topSpeed: 120, drivetrain: 'AWD', transmission: 'CVT',
    weight: 3450, mpg: 30, seats: 5,
    blurb: 'The crossover that convinced everyone to stop buying wagons.',
  },
  {
    id: 'nissan-rogue', make: 'Nissan', model: 'Rogue', years: '2021–2025',
    body: 'suv', country: 'Japan', rarity: 'common',
    engine: '1.5L VC-Turbo I3', power: 201, torque: 225,
    zeroToSixty: 8.2, topSpeed: 118, drivetrain: 'AWD', transmission: 'CVT',
    weight: 3500, mpg: 33, seats: 5,
    blurb: 'Runs a variable-compression three-cylinder, which is far weirder than it looks.',
  },
  {
    id: 'mazda-cx5', make: 'Mazda', model: 'CX-5', years: '2017–2025',
    body: 'suv', country: 'Japan', rarity: 'common',
    engine: '2.5L naturally aspirated I4', power: 187, torque: 186,
    zeroToSixty: 8.2, topSpeed: 124, drivetrain: 'AWD', transmission: '6-speed automatic',
    weight: 3700, mpg: 28, seats: 5,
    blurb: 'The one crossover that remembered steering feel is allowed to exist.',
  },
  {
    id: 'ford-explorer', make: 'Ford', model: 'Explorer', years: '2020–2025',
    body: 'suv', country: 'USA', rarity: 'common',
    engine: '2.3L turbocharged I4', power: 300, torque: 310,
    zeroToSixty: 6.5, topSpeed: 143, drivetrain: 'RWD', transmission: '10-speed automatic',
    weight: 4345, mpg: 24, seats: 7,
    blurb: 'Went rear-drive-based in 2020 and nobody outside forums noticed.',
  },
  {
    id: 'jeep-grand-cherokee', make: 'Jeep', model: 'Grand Cherokee', years: '2022–2025',
    body: 'suv', country: 'USA', rarity: 'common',
    engine: '3.6L Pentastar V6', power: 293, torque: 260,
    zeroToSixty: 7.6, topSpeed: 130, drivetrain: '4WD', transmission: '8-speed automatic',
    weight: 4500, mpg: 22, seats: 5,
    blurb: 'Genuinely capable off-road, overwhelmingly used for school runs.',
  },
  {
    id: 'toyota-highlander', make: 'Toyota', model: 'Highlander', years: '2020–2023',
    body: 'suv', country: 'Japan', rarity: 'common',
    engine: '3.5L V6', power: 295, torque: 263,
    zeroToSixty: 7.0, topSpeed: 130, drivetrain: 'AWD', transmission: '8-speed automatic',
    weight: 4300, mpg: 24, seats: 8,
    blurb: 'Three rows of unremarkable excellence.',
  },
  {
    id: 'ford-f150', make: 'Ford', model: 'F-150', years: '2021–2025',
    body: 'pickup', country: 'USA', rarity: 'common',
    engine: '3.5L twin-turbo EcoBoost V6', power: 400, torque: 500,
    zeroToSixty: 5.6, topSpeed: 107, drivetrain: '4WD', transmission: '10-speed automatic',
    weight: 4700, mpg: 20, seats: 5,
    blurb: 'Best-selling vehicle in America for four decades straight.',
  },
  {
    id: 'chevy-silverado', make: 'Chevrolet', model: 'Silverado 1500', years: '2019–2025',
    body: 'pickup', country: 'USA', rarity: 'common',
    engine: '5.3L V8', power: 355, torque: 383,
    zeroToSixty: 6.4, topSpeed: 112, drivetrain: '4WD', transmission: '10-speed automatic',
    weight: 4900, mpg: 19, seats: 5,
    blurb: 'The other one. Owners will tell you the difference at length.',
  },
  {
    id: 'ram-1500', make: 'Ram', model: '1500', years: '2019–2025',
    body: 'pickup', country: 'USA', rarity: 'common',
    engine: '5.7L HEMI V8', power: 395, torque: 410,
    zeroToSixty: 6.1, topSpeed: 118, drivetrain: '4WD', transmission: '8-speed automatic',
    weight: 5000, mpg: 20, seats: 5,
    blurb: 'Coil-sprung rear end makes it ride better than any truck has a right to.',
  },
  {
    id: 'toyota-tacoma', make: 'Toyota', model: 'Tacoma', years: '2016–2023',
    body: 'pickup', country: 'Japan', rarity: 'common',
    engine: '3.5L V6', power: 278, torque: 265,
    zeroToSixty: 7.7, topSpeed: 115, drivetrain: '4WD', transmission: '6-speed automatic',
    weight: 4400, mpg: 20, seats: 5,
    blurb: 'Depreciates so slowly that used ones cost more than sense allows.',
  },
  {
    id: 'ford-ranger', make: 'Ford', model: 'Ranger', years: '2019–2023',
    body: 'pickup', country: 'USA', rarity: 'common',
    engine: '2.3L turbocharged I4', power: 270, torque: 310,
    zeroToSixty: 6.4, topSpeed: 108, drivetrain: '4WD', transmission: '10-speed automatic',
    weight: 4441, mpg: 22, seats: 5,
    blurb: 'A midsize truck for people who parked a full-size once and gave up.',
  },
  {
    id: 'subaru-outback', make: 'Subaru', model: 'Outback', years: '2020–2025',
    body: 'wagon', country: 'Japan', rarity: 'common',
    engine: '2.5L flat-4', power: 182, torque: 176,
    zeroToSixty: 8.7, topSpeed: 130, drivetrain: 'AWD', transmission: 'CVT',
    weight: 3700, mpg: 29, seats: 5,
    blurb: 'A lifted wagon that refused to admit it is a crossover. Respect.',
  },
  {
    id: 'honda-odyssey', make: 'Honda', model: 'Odyssey', years: '2018–2025',
    body: 'minivan', country: 'Japan', rarity: 'common',
    engine: '3.5L V6', power: 280, torque: 262,
    zeroToSixty: 7.0, topSpeed: 120, drivetrain: 'FWD', transmission: '10-speed automatic',
    weight: 4600, mpg: 22, seats: 8,
    blurb: 'Faster to 60 than a 1990s BMW. Carries eight people and their regrets.',
  },
  {
    id: 'chrysler-pacifica', make: 'Chrysler', model: 'Pacifica', years: '2017–2025',
    body: 'minivan', country: 'USA', rarity: 'common',
    engine: '3.6L Pentastar V6', power: 287, torque: 262,
    zeroToSixty: 7.3, topSpeed: 115, drivetrain: 'FWD', transmission: '9-speed automatic',
    weight: 4500, mpg: 22, seats: 7,
    blurb: 'Seats that fold flat into the floor. Peak minivan engineering.',
  },
  {
    id: 'ford-transit', make: 'Ford', model: 'Transit', years: '2020–2025',
    body: 'van', country: 'USA', rarity: 'common',
    engine: '3.5L V6', power: 275, torque: 262,
    zeroToSixty: 8.5, topSpeed: 100, drivetrain: 'RWD', transmission: '10-speed automatic',
    weight: 5000, mpg: 18, seats: 2,
    blurb: 'Half of these are plumbers, half are someone’s entire apartment.',
  },
  {
    id: 'mercedes-sprinter', make: 'Mercedes-Benz', model: 'Sprinter', years: '2019–2025',
    body: 'van', country: 'Germany', rarity: 'common',
    engine: '2.0L turbodiesel I4', power: 170, torque: 295,
    zeroToSixty: 11.0, topSpeed: 100, drivetrain: 'RWD', transmission: '9-speed automatic',
    weight: 5300, mpg: 22, seats: 2,
    blurb: 'The three-pointed star of the delivery world, and every van-life channel.',
  },

  // -------------------------------------------------------------- uncommon
  {
    id: 'subaru-wrx', make: 'Subaru', model: 'WRX', years: '2022–2025',
    body: 'sedan', country: 'Japan', rarity: 'uncommon',
    engine: '2.4L turbocharged flat-4', power: 271, torque: 258,
    zeroToSixty: 5.4, topSpeed: 155, drivetrain: 'AWD', transmission: '6-speed manual',
    weight: 3300, mpg: 22, seats: 5,
    blurb: 'Rally homologation energy, unresolved plastic cladding debate.',
  },
  {
    id: 'vw-golf-gti', make: 'Volkswagen', model: 'Golf GTI', years: '2022–2025',
    body: 'hatchback', country: 'Germany', rarity: 'uncommon',
    engine: '2.0L turbocharged I4', power: 241, torque: 273,
    zeroToSixty: 5.6, topSpeed: 155, drivetrain: 'FWD', transmission: '7-speed DSG',
    weight: 3150, mpg: 27, seats: 5,
    blurb: 'The hot hatch that invented the category and still argues it perfected it.',
  },
  {
    id: 'honda-civic-type-r', make: 'Honda', model: 'Civic Type R', years: '2023–2025',
    body: 'hatchback', country: 'Japan', rarity: 'uncommon',
    engine: '2.0L turbocharged I4 (K20C1)', power: 315, torque: 310,
    zeroToSixty: 5.0, topSpeed: 169, drivetrain: 'FWD', transmission: '6-speed manual',
    weight: 3188, mpg: 24, seats: 4,
    blurb: 'Front-wheel-drive Nurburgring record holder. Manual only, forever.',
  },
  {
    id: 'mini-cooper-s', make: 'MINI', model: 'Cooper S', years: '2021–2024',
    body: 'hatchback', country: 'United Kingdom', rarity: 'uncommon',
    engine: '2.0L turbocharged I4', power: 189, torque: 207,
    zeroToSixty: 6.3, topSpeed: 146, drivetrain: 'FWD', transmission: '7-speed DCT',
    weight: 2892, mpg: 28, seats: 4,
    blurb: 'Go-kart handling, dinner-plate infotainment, questionable reliability.',
  },
  {
    id: 'mazda-mx5', make: 'Mazda', model: 'MX-5 Miata (ND)', years: '2019–2025',
    body: 'convertible', country: 'Japan', rarity: 'uncommon',
    engine: '2.0L naturally aspirated I4', power: 181, torque: 151,
    zeroToSixty: 5.7, topSpeed: 135, drivetrain: 'RWD', transmission: '6-speed manual',
    weight: 2341, mpg: 29, seats: 2,
    blurb: 'The answer is always Miata. This is not up for discussion.',
  },
  {
    id: 'toyota-gr86', make: 'Toyota', model: 'GR86', years: '2022–2025',
    body: 'coupe', country: 'Japan', rarity: 'uncommon',
    engine: '2.4L flat-4', power: 228, torque: 184,
    zeroToSixty: 5.9, topSpeed: 140, drivetrain: 'RWD', transmission: '6-speed manual',
    weight: 2811, mpg: 25, seats: 4,
    blurb: 'Cheap, light, rear-drive and allergic to understeer.',
  },
  {
    id: 'ford-mustang-gt', make: 'Ford', model: 'Mustang GT', years: '2018–2023',
    body: 'coupe', country: 'USA', rarity: 'uncommon',
    engine: '5.0L Coyote V8', power: 460, torque: 420,
    zeroToSixty: 4.2, topSpeed: 155, drivetrain: 'RWD', transmission: '6-speed manual',
    weight: 3705, mpg: 19, seats: 4,
    blurb: 'Revs to 7,500. Please do not leave the car meet sideways.',
  },
  {
    id: 'chevy-camaro-ss', make: 'Chevrolet', model: 'Camaro SS', years: '2016–2024',
    body: 'coupe', country: 'USA', rarity: 'uncommon',
    engine: '6.2L LT1 V8', power: 455, torque: 455,
    zeroToSixty: 4.0, topSpeed: 165, drivetrain: 'RWD', transmission: '6-speed manual',
    weight: 3685, mpg: 20, seats: 4,
    blurb: 'Handles brilliantly. You cannot see out of it at all.',
  },
  {
    id: 'dodge-challenger-rt', make: 'Dodge', model: 'Challenger R/T', years: '2015–2023',
    body: 'coupe', country: 'USA', rarity: 'uncommon',
    engine: '5.7L HEMI V8', power: 375, torque: 410,
    zeroToSixty: 5.6, topSpeed: 155, drivetrain: 'RWD', transmission: '6-speed manual',
    weight: 4100, mpg: 18, seats: 5,
    blurb: 'A 1970 muscle car that never stopped being sold. Enormous and unbothered.',
  },
  {
    id: 'tesla-model-3', make: 'Tesla', model: 'Model 3 Long Range', years: '2021–2025',
    body: 'sedan', country: 'USA', rarity: 'uncommon',
    engine: 'Dual electric motors', power: 346, torque: 389,
    zeroToSixty: 4.2, topSpeed: 145, drivetrain: 'AWD', transmission: 'Single-speed',
    weight: 3862, range: 358, fuel: 'electric', seats: 5,
    blurb: 'Silent, quick, and responsible for most of the panel-gap discourse online.',
  },
  {
    id: 'bmw-330i', make: 'BMW', model: '330i (G20)', years: '2019–2025',
    body: 'sedan', country: 'Germany', rarity: 'uncommon',
    engine: '2.0L turbocharged I4', power: 255, torque: 295,
    zeroToSixty: 5.6, topSpeed: 155, drivetrain: 'RWD', transmission: '8-speed automatic',
    weight: 3600, mpg: 30, seats: 5,
    blurb: 'The sports sedan benchmark, still, whatever the internet insists.',
  },
  {
    id: 'audi-a4', make: 'Audi', model: 'A4 45 TFSI', years: '2020–2024',
    body: 'sedan', country: 'Germany', rarity: 'uncommon',
    engine: '2.0L turbocharged I4', power: 261, torque: 273,
    zeroToSixty: 5.2, topSpeed: 155, drivetrain: 'AWD', transmission: '7-speed DCT',
    weight: 3700, mpg: 27, seats: 5,
    blurb: 'Quattro grip and an interior that makes rivals look unfinished.',
  },
  {
    id: 'mercedes-c300', make: 'Mercedes-Benz', model: 'C 300', years: '2022–2025',
    body: 'sedan', country: 'Germany', rarity: 'uncommon',
    engine: '2.0L turbocharged I4 with mild hybrid', power: 255, torque: 295,
    zeroToSixty: 5.9, topSpeed: 130, drivetrain: 'RWD', transmission: '9-speed automatic',
    weight: 3700, mpg: 28, seats: 5,
    blurb: 'A baby S-Class, which is exactly the pitch and exactly the appeal.',
  },
  {
    id: 'lexus-rx350', make: 'Lexus', model: 'RX 350', years: '2023–2025',
    body: 'suv', country: 'Japan', rarity: 'uncommon',
    engine: '2.4L turbocharged I4', power: 275, torque: 317,
    zeroToSixty: 7.2, topSpeed: 124, drivetrain: 'AWD', transmission: '8-speed automatic',
    weight: 4300, mpg: 25, seats: 5,
    blurb: 'The luxury crossover that basically created the segment in 1998.',
  },
  {
    id: 'volvo-xc90', make: 'Volvo', model: 'XC90 B6', years: '2020–2025',
    body: 'suv', country: 'Sweden', rarity: 'uncommon',
    engine: '2.0L supercharged + turbocharged I4', power: 295, torque: 310,
    zeroToSixty: 6.2, topSpeed: 112, drivetrain: 'AWD', transmission: '8-speed automatic',
    weight: 4600, mpg: 23, seats: 7,
    blurb: 'Limited to 112 mph on purpose. Sweden has opinions about safety.',
  },
  {
    id: 'jeep-wrangler', make: 'Jeep', model: 'Wrangler Rubicon', years: '2018–2025',
    body: 'suv', country: 'USA', rarity: 'uncommon',
    engine: '3.6L Pentastar V6', power: 285, torque: 260,
    zeroToSixty: 6.8, topSpeed: 112, drivetrain: '4WD', transmission: '8-speed automatic',
    weight: 4200, mpg: 20, seats: 5,
    blurb: 'Solid axles, removable doors, and the aerodynamics of a filing cabinet.',
  },
  {
    id: 'ford-bronco', make: 'Ford', model: 'Bronco', years: '2021–2025',
    body: 'suv', country: 'USA', rarity: 'uncommon',
    engine: '2.7L twin-turbo V6', power: 330, torque: 415,
    zeroToSixty: 5.9, topSpeed: 110, drivetrain: '4WD', transmission: '10-speed automatic',
    weight: 4800, mpg: 19, seats: 5,
    blurb: 'Came back after 25 years and immediately had a two-year waiting list.',
  },
  {
    id: 'fiat-500', make: 'Fiat', model: '500', years: '2012–2019',
    body: 'hatchback', country: 'Italy', rarity: 'uncommon',
    engine: '1.4L I4', power: 101, torque: 98,
    zeroToSixty: 9.5, topSpeed: 110, drivetrain: 'FWD', transmission: '5-speed manual',
    weight: 2366, mpg: 34, seats: 4,
    blurb: 'Charm-to-horsepower ratio off the charts.',
  },

  // ------------------------------------------------------------------ rare
  {
    id: 'porsche-911-carrera', make: 'Porsche', model: '911 Carrera (992)', years: '2019–2025',
    body: 'coupe', country: 'Germany', rarity: 'rare',
    engine: '3.0L twin-turbo flat-6', power: 379, torque: 331,
    zeroToSixty: 4.0, topSpeed: 182, drivetrain: 'RWD', transmission: '8-speed PDK',
    weight: 3354, mpg: 20, seats: 4,
    blurb: 'Engine still behind the rear axle after 60 years of engineers begging otherwise.',
  },
  {
    id: 'porsche-718-cayman', make: 'Porsche', model: '718 Cayman', years: '2017–2025',
    body: 'coupe', country: 'Germany', rarity: 'rare',
    engine: '2.0L turbocharged flat-4', power: 300, torque: 280,
    zeroToSixty: 4.9, topSpeed: 170, drivetrain: 'RWD', transmission: '6-speed manual',
    weight: 3054, mpg: 24, seats: 2,
    blurb: 'Mid-engined and arguably better balanced than the 911. Porsche knows.',
  },
  {
    id: 'corvette-c8', make: 'Chevrolet', model: 'Corvette C8 Stingray', years: '2020–2025',
    body: 'coupe', country: 'USA', rarity: 'rare',
    engine: '6.2L LT2 V8', power: 495, torque: 470,
    zeroToSixty: 2.9, topSpeed: 194, drivetrain: 'RWD', transmission: '8-speed DCT',
    weight: 3535, mpg: 19, seats: 2,
    blurb: 'America moved the engine behind the driver and beat supercars on price.',
  },
  {
    id: 'bmw-m3', make: 'BMW', model: 'M3 Competition (G80)', years: '2021–2025',
    body: 'sedan', country: 'Germany', rarity: 'rare',
    engine: '3.0L twin-turbo I6 (S58)', power: 503, torque: 479,
    zeroToSixty: 3.8, topSpeed: 180, drivetrain: 'RWD', transmission: '8-speed automatic',
    weight: 3900, mpg: 19, seats: 5,
    blurb: 'Ferociously fast. The grille remains a topic of active conflict.',
  },
  {
    id: 'audi-rs5', make: 'Audi', model: 'RS 5', years: '2018–2024',
    body: 'coupe', country: 'Germany', rarity: 'rare',
    engine: '2.9L twin-turbo V6', power: 444, torque: 442,
    zeroToSixty: 3.7, topSpeed: 174, drivetrain: 'AWD', transmission: '8-speed automatic',
    weight: 3946, mpg: 21, seats: 4,
    blurb: 'Launches off the line like gravity is negotiable.',
  },
  {
    id: 'amg-c63', make: 'Mercedes-AMG', model: 'C 63 S (W205)', years: '2015–2021',
    body: 'sedan', country: 'Germany', rarity: 'rare',
    engine: '4.0L twin-turbo V8 (M177)', power: 503, torque: 516,
    zeroToSixty: 3.8, topSpeed: 180, drivetrain: 'RWD', transmission: '9-speed automatic',
    weight: 3900, mpg: 20, seats: 5,
    blurb: 'The last V8 C63. Sounds like a thunderstorm having a bad day.',
  },
  {
    id: 'audi-rs6-avant', make: 'Audi', model: 'RS 6 Avant (C8)', years: '2020–2025',
    body: 'wagon', country: 'Germany', rarity: 'rare',
    engine: '4.0L twin-turbo V8', power: 591, torque: 590,
    zeroToSixty: 3.5, topSpeed: 190, drivetrain: 'AWD', transmission: '8-speed automatic',
    weight: 4784, mpg: 17, seats: 5,
    blurb: 'A 190 mph estate car. The correct answer to almost every question.',
  },
  {
    id: 'nissan-gtr-r35', make: 'Nissan', model: 'GT-R (R35)', years: '2017–2024',
    body: 'coupe', country: 'Japan', rarity: 'rare',
    engine: '3.8L twin-turbo V6 (VR38DETT)', power: 565, torque: 467,
    zeroToSixty: 2.9, topSpeed: 196, drivetrain: 'AWD', transmission: '6-speed DCT',
    weight: 3933, mpg: 18, seats: 4,
    blurb: 'Godzilla. Hand-built engine, one badge per assembler, physics-defying launch control.',
  },
  {
    id: 'toyota-supra-a90', make: 'Toyota', model: 'GR Supra 3.0 (A90)', years: '2020–2025',
    body: 'coupe', country: 'Japan', rarity: 'rare',
    engine: '3.0L turbocharged I6 (B58)', power: 382, torque: 368,
    zeroToSixty: 3.9, topSpeed: 155, drivetrain: 'RWD', transmission: '6-speed manual',
    weight: 3400, mpg: 25, seats: 2,
    blurb: 'Yes, the engine is BMW’s. No, it does not make it slower.',
  },
  {
    id: 'dodge-hellcat', make: 'Dodge', model: 'Challenger SRT Hellcat', years: '2015–2023',
    body: 'coupe', country: 'USA', rarity: 'rare',
    engine: '6.2L supercharged HEMI V8', power: 717, torque: 656,
    zeroToSixty: 3.6, topSpeed: 199, drivetrain: 'RWD', transmission: '8-speed automatic',
    weight: 4450, mpg: 16, seats: 5,
    blurb: 'The supercharger whine is audible from a different postcode.',
  },
  {
    id: 'jaguar-ftype-r', make: 'Jaguar', model: 'F-Type R', years: '2021–2024',
    body: 'coupe', country: 'United Kingdom', rarity: 'rare',
    engine: '5.0L supercharged V8', power: 575, torque: 516,
    zeroToSixty: 3.5, topSpeed: 186, drivetrain: 'AWD', transmission: '8-speed automatic',
    weight: 3900, mpg: 18, seats: 2,
    blurb: 'Crackles and bangs on the overrun like it is being paid to.',
  },
  {
    id: 'range-rover', make: 'Land Rover', model: 'Range Rover P530', years: '2022–2025',
    body: 'suv', country: 'United Kingdom', rarity: 'rare',
    engine: '4.4L twin-turbo V8', power: 523, torque: 553,
    zeroToSixty: 4.4, topSpeed: 155, drivetrain: 'AWD', transmission: '8-speed automatic',
    weight: 5600, mpg: 18, seats: 5,
    blurb: 'A drawing room that can ford 3 feet of water.',
  },
  {
    id: 'tesla-model-s-plaid', make: 'Tesla', model: 'Model S Plaid', years: '2021–2025',
    body: 'sedan', country: 'USA', rarity: 'rare',
    engine: 'Tri-motor electric', power: 1020, torque: 1050,
    zeroToSixty: 1.99, topSpeed: 200, drivetrain: 'AWD', transmission: 'Single-speed',
    weight: 4766, range: 396, fuel: 'electric', seats: 5,
    blurb: 'Sub-two seconds to 60 in a four-door family car. The world got strange.',
  },
  {
    id: 'vw-beetle-classic', make: 'Volkswagen', model: 'Beetle (Type 1)', years: '1938–2003',
    body: 'coupe', country: 'Germany', rarity: 'rare',
    engine: '1.6L air-cooled flat-4', power: 60, torque: 82,
    zeroToSixty: 17.0, topSpeed: 82, drivetrain: 'RWD', transmission: '4-speed manual',
    weight: 1800, mpg: 27, seats: 4,
    blurb: '21.5 million built. Air-cooled, rear-engined, unkillable.',
  },
  {
    id: 'vw-bus-t2', make: 'Volkswagen', model: 'Type 2 Bus', years: '1967–1979',
    body: 'van', country: 'Germany', rarity: 'rare',
    engine: '1.8L air-cooled flat-4', power: 67, torque: 90,
    zeroToSixty: 24.0, topSpeed: 75, drivetrain: 'RWD', transmission: '4-speed manual',
    weight: 2900, mpg: 22, seats: 8,
    blurb: 'Slower than most bicycles downhill. Worth more than most new cars.',
  },

  // ------------------------------------------------------------------ epic
  {
    id: 'ferrari-488-gtb', make: 'Ferrari', model: '488 GTB', years: '2015–2019',
    body: 'coupe', country: 'Italy', rarity: 'epic',
    engine: '3.9L twin-turbo V8 (F154)', power: 661, torque: 561,
    zeroToSixty: 3.0, topSpeed: 205, drivetrain: 'RWD', transmission: '7-speed DCT',
    weight: 3252, mpg: 18, seats: 2,
    blurb: 'International Engine of the Year three times running.',
  },
  {
    id: 'lamborghini-huracan', make: 'Lamborghini', model: 'Huracán EVO', years: '2019–2024',
    body: 'coupe', country: 'Italy', rarity: 'epic',
    engine: '5.2L naturally aspirated V10', power: 631, torque: 442,
    zeroToSixty: 2.9, topSpeed: 202, drivetrain: 'AWD', transmission: '7-speed DCT',
    weight: 3400, mpg: 15, seats: 2,
    blurb: 'One of the last naturally aspirated V10s. Revs to 8,500 and screams doing it.',
  },
  {
    id: 'mclaren-720s', make: 'McLaren', model: '720S', years: '2017–2022',
    body: 'coupe', country: 'United Kingdom', rarity: 'epic',
    engine: '4.0L twin-turbo V8', power: 710, torque: 568,
    zeroToSixty: 2.8, topSpeed: 212, drivetrain: 'RWD', transmission: '7-speed DCT',
    weight: 3186, mpg: 18, seats: 2,
    blurb: 'Carbon tub, dihedral doors, and a habit of embarrassing hypercars.',
  },
  {
    id: 'audi-r8-v10', make: 'Audi', model: 'R8 V10 Performance', years: '2019–2023',
    body: 'coupe', country: 'Germany', rarity: 'epic',
    engine: '5.2L naturally aspirated V10', power: 602, torque: 413,
    zeroToSixty: 3.2, topSpeed: 205, drivetrain: 'AWD', transmission: '7-speed DCT',
    weight: 3737, mpg: 16, seats: 2,
    blurb: 'A supercar you could genuinely commute in. Shares its heart with the Huracán.',
  },
  {
    id: 'porsche-911-turbo-s', make: 'Porsche', model: '911 Turbo S (992)', years: '2020–2025',
    body: 'coupe', country: 'Germany', rarity: 'epic',
    engine: '3.7L twin-turbo flat-6', power: 640, torque: 590,
    zeroToSixty: 2.6, topSpeed: 205, drivetrain: 'AWD', transmission: '8-speed PDK',
    weight: 3636, mpg: 18, seats: 4,
    blurb: 'All-weather, all-year, all-conquering. Genuinely rains-and-still-does-2.6.',
  },
  {
    id: 'corvette-z06-c8', make: 'Chevrolet', model: 'Corvette Z06 (C8)', years: '2023–2025',
    body: 'coupe', country: 'USA', rarity: 'epic',
    engine: '5.5L flat-plane V8 (LT6)', power: 670, torque: 460,
    zeroToSixty: 2.6, topSpeed: 189, drivetrain: 'RWD', transmission: '8-speed DCT',
    weight: 3670, mpg: 15, seats: 2,
    blurb: 'Highest-output naturally aspirated V8 ever put in a production car. 8,600 rpm.',
  },
  {
    id: 'aston-db11-v12', make: 'Aston Martin', model: 'DB11 V12', years: '2017–2023',
    body: 'coupe', country: 'United Kingdom', rarity: 'epic',
    engine: '5.2L twin-turbo V12', power: 630, torque: 516,
    zeroToSixty: 3.6, topSpeed: 208, drivetrain: 'RWD', transmission: '8-speed automatic',
    weight: 3902, mpg: 18, seats: 4,
    blurb: 'A grand tourer that treats continents as a weekend problem.',
  },
  {
    id: 'bentley-continental-gt', make: 'Bentley', model: 'Continental GT W12', years: '2018–2023',
    body: 'coupe', country: 'United Kingdom', rarity: 'epic',
    engine: '6.0L twin-turbo W12', power: 626, torque: 664,
    zeroToSixty: 3.5, topSpeed: 208, drivetrain: 'AWD', transmission: '8-speed DCT',
    weight: 5000, mpg: 15, seats: 4,
    blurb: 'Two and a half tons that hits 60 in 3.5 seconds without spilling your coffee.',
  },
  {
    id: 'rolls-royce-ghost', make: 'Rolls-Royce', model: 'Ghost', years: '2021–2025',
    body: 'sedan', country: 'United Kingdom', rarity: 'epic',
    engine: '6.75L twin-turbo V12', power: 563, torque: 627,
    zeroToSixty: 4.6, topSpeed: 155, drivetrain: 'AWD', transmission: '8-speed automatic',
    weight: 5628, mpg: 14, seats: 5,
    blurb: 'Uses a camera to read the road ahead and pre-adjust the suspension. Obviously.',
  },
  {
    id: 'nissan-skyline-r34', make: 'Nissan', model: 'Skyline GT-R (R34)', years: '1999–2002',
    body: 'coupe', country: 'Japan', rarity: 'epic',
    engine: '2.6L twin-turbo I6 (RB26DETT)', power: 276, torque: 289,
    zeroToSixty: 4.9, topSpeed: 165, drivetrain: 'AWD', transmission: '6-speed manual',
    weight: 3400, mpg: 18, seats: 4,
    blurb: 'Officially 276 hp under a gentlemen’s agreement. Nobody believed it then either.',
  },

  // ------------------------------------------------------------- legendary
  {
    id: 'bugatti-chiron', make: 'Bugatti', model: 'Chiron', years: '2016–2022',
    body: 'coupe', country: 'France', rarity: 'legendary',
    engine: '8.0L quad-turbo W16', power: 1479, torque: 1180,
    zeroToSixty: 2.4, topSpeed: 261, drivetrain: 'AWD', transmission: '7-speed DCT',
    weight: 4400, mpg: 11, seats: 2,
    blurb: 'Sixteen cylinders, four turbos, ten radiators. Burns a full tank in nine minutes flat out.',
  },
  {
    id: 'koenigsegg-jesko', make: 'Koenigsegg', model: 'Jesko Absolut', years: '2023–2025',
    body: 'coupe', country: 'Sweden', rarity: 'legendary',
    engine: '5.0L twin-turbo V8', power: 1280, torque: 1106,
    zeroToSixty: 2.5, topSpeed: 300, drivetrain: 'RWD', transmission: '9-speed LST',
    weight: 3131, mpg: 12, seats: 2,
    blurb: '1,600 hp on E85. The nine-speed gearbox has no synchros and shifts in 20 milliseconds.',
  },
  {
    id: 'ferrari-laferrari', make: 'Ferrari', model: 'LaFerrari', years: '2013–2018',
    body: 'coupe', country: 'Italy', rarity: 'legendary',
    engine: '6.3L V12 with HY-KERS hybrid', power: 950, torque: 663,
    zeroToSixty: 2.4, topSpeed: 217, drivetrain: 'RWD', transmission: '7-speed DCT',
    weight: 3495, mpg: 14, seats: 2,
    blurb: '499 built. Ferrari chose who was allowed to buy one.',
  },
  {
    id: 'mclaren-p1', make: 'McLaren', model: 'P1', years: '2013–2015',
    body: 'coupe', country: 'United Kingdom', rarity: 'legendary',
    engine: '3.8L twin-turbo V8 hybrid', power: 903, torque: 664,
    zeroToSixty: 2.7, topSpeed: 217, drivetrain: 'RWD', transmission: '7-speed DCT',
    weight: 3411, mpg: 17, seats: 2,
    blurb: 'Active aero, IPAS boost button, and 375 examples in existence.',
  },
  {
    id: 'porsche-918', make: 'Porsche', model: '918 Spyder', years: '2013–2015',
    body: 'convertible', country: 'Germany', rarity: 'legendary',
    engine: '4.6L V8 with twin electric motors', power: 887, torque: 944,
    zeroToSixty: 2.5, topSpeed: 214, drivetrain: 'AWD', transmission: '7-speed PDK',
    weight: 3715, mpg: 22, seats: 2,
    blurb: 'The hybrid hypercar that made the other two look late to the idea.',
  },
  {
    id: 'pagani-huayra', make: 'Pagani', model: 'Huayra', years: '2012–2018',
    body: 'coupe', country: 'Italy', rarity: 'legendary',
    engine: '6.0L twin-turbo V12 (AMG)', power: 720, torque: 738,
    zeroToSixty: 2.8, topSpeed: 238, drivetrain: 'RWD', transmission: '7-speed sequential',
    weight: 2976, mpg: 13, seats: 2,
    blurb: 'Four active aero flaps and titanium bolts with the Pagani logo on each head.',
  },
  {
    id: 'lamborghini-countach', make: 'Lamborghini', model: 'Countach LP400', years: '1974–1978',
    body: 'coupe', country: 'Italy', rarity: 'legendary',
    engine: '4.0L naturally aspirated V12', power: 375, torque: 268,
    zeroToSixty: 5.6, topSpeed: 179, drivetrain: 'RWD', transmission: '5-speed manual',
    weight: 2900, mpg: 10, seats: 2,
    blurb: 'The bedroom poster. Visibility rearward was zero and nobody cared.',
  },
  {
    id: 'ford-gt-2017', make: 'Ford', model: 'GT', years: '2017–2022',
    body: 'coupe', country: 'USA', rarity: 'legendary',
    engine: '3.5L twin-turbo EcoBoost V6', power: 647, torque: 550,
    zeroToSixty: 2.8, topSpeed: 216, drivetrain: 'RWD', transmission: '7-speed DCT',
    weight: 3354, mpg: 14, seats: 2,
    blurb: 'Won Le Mans in 2016, fifty years after the original did. You had to apply to buy one.',
  },
  {
    id: 'dodge-viper-acr', make: 'Dodge', model: 'Viper ACR', years: '2016',
    body: 'coupe', country: 'USA', rarity: 'legendary',
    engine: '8.4L naturally aspirated V10', power: 645, torque: 600,
    zeroToSixty: 3.3, topSpeed: 177, drivetrain: 'RWD', transmission: '6-speed manual',
    weight: 3374, mpg: 14, seats: 2,
    blurb: 'No traction control worth the name. Set 13 track records and frightened everyone.',
  },
  {
    id: 'mazda-rx7-fd', make: 'Mazda', model: 'RX-7 (FD)', years: '1992–2002',
    body: 'coupe', country: 'Japan', rarity: 'legendary',
    engine: '1.3L sequential twin-turbo rotary (13B-REW)', power: 255, torque: 217,
    zeroToSixty: 5.3, topSpeed: 156, drivetrain: 'RWD', transmission: '5-speed manual',
    weight: 2800, mpg: 18, seats: 4,
    blurb: 'A 1.3-litre engine with no pistons. Perfect 50:50 balance, imperfect apex seals.',
  },
  {
    id: 'honda-nsx-na1', make: 'Honda', model: 'NSX (NA1)', years: '1990–2005',
    body: 'coupe', country: 'Japan', rarity: 'legendary',
    engine: '3.0L V6 with VTEC', power: 270, torque: 210,
    zeroToSixty: 5.7, topSpeed: 168, drivetrain: 'RWD', transmission: '5-speed manual',
    weight: 3010, mpg: 20, seats: 2,
    blurb: 'Ayrton Senna helped tune the chassis. First all-aluminium production monocoque.',
  },
  {
    id: 'toyota-ae86', make: 'Toyota', model: 'Corolla AE86 Trueno', years: '1983–1987',
    body: 'coupe', country: 'Japan', rarity: 'legendary',
    engine: '1.6L I4 (4A-GE)', power: 128, torque: 110,
    zeroToSixty: 8.3, topSpeed: 122, drivetrain: 'RWD', transmission: '5-speed manual',
    weight: 2200, mpg: 27, seats: 4,
    blurb: 'Hachi-Roku. Slow, light, rear-drive and responsible for drifting as a sport.',
  },
];

export const CARS_BY_ID = new Map(CARS.map((c) => [c.id, c]));

export function displayName(car) {
  return `${car.make} ${car.model}`;
}
